name: "helm-bitbucket"
version: "1.0.0"
description: |-
  Let's you use private gitlab repositories easily
downloaders:
- command: "getfile.sh"
  protocols:
    - "gitlab"
    - "gitlab-https"
    - "github"
    - "github-https"
    - "bitbucket"
    - "bitbucket-https"
